# Change these first
owner: usizy # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Usizy
    url: https://usizy.com
  - name: Dashboard
    url: https://usizy.com/dashboard/health-check/
  - name: Help
    url: https://help3.usizy.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.usizy.com
  # baseUrl: /your-repo-name
  logoUrl: https://media.usizy.es/website/images/Usizy_Logo-DM.svg
  name: Usizy
  introTitle: "The best sizing tool for retailers"
  introMessage: Usizy uptime monitor and status website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 14 * * *"
  responseTime: "0 13 * * *"
  staticSite: "0 15 * * *"
  summary: "0 14 * * *"
  updateTemplate: "0 14 * * *"
  updates: "0 17 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
